// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTag = "tags"

// Tag mapped from table <tags>
type Tag struct {
	TagID      uint64         `gorm:"column:tag_id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"tag_id"`
	Name       string         `gorm:"column:name;type:varchar(50);not null;uniqueIndex:name,priority:1" json:"name"`
	PostsCount uint64         `gorm:"column:posts_count;type:bigint(20) unsigned;not null" json:"posts_count"`
	CreatedAt  time.Time      `gorm:"column:created_at;type:timestamp;not null;default:current_timestamp()" json:"created_at"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp" json:"deleted_at"`
	UpdatedAt  time.Time      `gorm:"column:updated_at;type:timestamp" json:"updated_at"`
}

// TableName Tag's table name
func (*Tag) TableName() string {
	return TableNameTag
}
