// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNameValidation = "validations"

// Validation mapped from table <validations>
type Validation struct {
	ValidationID uint64         `gorm:"column:validation_id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"validation_id"`
	Class        string         `gorm:"column:class;type:varchar(20);not null" json:"class"`
	ObjectID     uint64         `gorm:"column:object_id;type:bigint(20) unsigned;not null" json:"object_id"`
	CreatedAt    time.Time      `gorm:"column:created_at;type:timestamp;not null;default:current_timestamp()" json:"created_at"`
	DeletedAt    gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp" json:"deleted_at"`
	UpdatedAt    time.Time      `gorm:"column:updated_at;type:timestamp" json:"updated_at"`
}

// TableName Validation's table name
func (*Validation) TableName() string {
	return TableNameValidation
}
