// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePostsReaction = "posts_reactions"

// PostsReaction mapped from table <posts_reactions>
type PostsReaction struct {
	UserID    uint64         `gorm:"column:user_id;type:bigint(20) unsigned;not null;index:user_id,priority:1" json:"user_id"`
	Reaction  string         `gorm:"column:reaction;type:varchar(20);not null;index:user_id,priority:2" json:"reaction"`
	PostID    uint64         `gorm:"column:post_id;type:bigint(20) unsigned;not null;index:post_id,priority:1" json:"post_id"`
	CreatedAt time.Time      `gorm:"column:created_at;type:timestamp;not null;default:current_timestamp()" json:"created_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp" json:"deleted_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:timestamp" json:"updated_at"`
}

// TableName PostsReaction's table name
func (*PostsReaction) TableName() string {
	return TableNamePostsReaction
}
