// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNamePostsPriority = "posts_priority"

// PostsPriority mapped from table <posts_priority>
type PostsPriority struct {
	PostID     uint64         `gorm:"column:post_id;type:bigint(20) unsigned;not null;index:post_id,priority:1" json:"post_id"`
	PostWeight uint32         `gorm:"column:post_weight;type:int(16) unsigned;not null;index:post_weight,priority:1" json:"post_weight"`
	CreatedAt  time.Time      `gorm:"column:created_at;type:timestamp;not null;default:current_timestamp()" json:"created_at"`
	DeletedAt  gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp" json:"deleted_at"`
	UpdatedAt  time.Time      `gorm:"column:updated_at;type:timestamp" json:"updated_at"`
}

// TableName PostsPriority's table name
func (*PostsPriority) TableName() string {
	return TableNamePostsPriority
}
