// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"fmt"
	"testing"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := db.AutoMigrate(&models.ValidationsEmail{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&models.ValidationsEmail{}) fail: %s", err)
	}
}

func Test_validationsEmailQuery(t *testing.T) {
	validationsEmail := newValidationsEmail(db)
	validationsEmail = *validationsEmail.As(validationsEmail.TableName())
	_do := validationsEmail.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(validationsEmail.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <validations_email> fail:", err)
		return
	}

	_, ok := validationsEmail.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from validationsEmail success")
	}

	err = _do.Create(&models.ValidationsEmail{})
	if err != nil {
		t.Error("create item in table <validations_email> fail:", err)
	}

	err = _do.Save(&models.ValidationsEmail{})
	if err != nil {
		t.Error("create item in table <validations_email> fail:", err)
	}

	err = _do.CreateInBatches([]*models.ValidationsEmail{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <validations_email> fail:", err)
	}

	_, err = _do.Select(validationsEmail.ALL).Take()
	if err != nil {
		t.Error("Take() on table <validations_email> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <validations_email> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <validations_email> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <validations_email> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*models.ValidationsEmail{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <validations_email> fail:", err)
	}

	_, err = _do.Select(validationsEmail.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <validations_email> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <validations_email> fail:", err)
	}

	_, err = _do.Select(validationsEmail.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <validations_email> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <validations_email> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <validations_email> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <validations_email> fail:", err)
	}

	_, err = _do.ScanByPage(&models.ValidationsEmail{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <validations_email> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <validations_email> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <validations_email> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), clause.PrimaryKey)

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <validations_email> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <validations_email> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <validations_email> fail:", err)
	}
}
