// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCommentsReaction = "comments_reactions"

// CommentsReaction mapped from table <comments_reactions>
type CommentsReaction struct {
	CommentID uint64         `gorm:"column:comment_id;type:bigint(20) unsigned;not null;index:comment_id,priority:1" json:"comment_id"`
	Reaction  string         `gorm:"column:reaction;type:varchar(20);not null;index:user_id,priority:2" json:"reaction"`
	UserID    uint64         `gorm:"column:user_id;type:bigint(20) unsigned;not null;index:user_id,priority:1" json:"user_id"`
	CreatedAt time.Time      `gorm:"column:created_at;type:timestamp;not null;default:current_timestamp()" json:"created_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp" json:"deleted_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:timestamp" json:"updated_at"`
}

// TableName CommentsReaction's table name
func (*CommentsReaction) TableName() string {
	return TableNameCommentsReaction
}
