// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q             = new(Query)
	Post          *post
	PostsPriority *postsPriority
	PostsReaction *postsReaction
	PostsTag      *postsTag
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Post = &Q.Post
	PostsPriority = &Q.PostsPriority
	PostsReaction = &Q.PostsReaction
	PostsTag = &Q.PostsTag
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:            db,
		Post:          newPost(db, opts...),
		PostsPriority: newPostsPriority(db, opts...),
		PostsReaction: newPostsReaction(db, opts...),
		PostsTag:      newPostsTag(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Post          post
	PostsPriority postsPriority
	PostsReaction postsReaction
	PostsTag      postsTag
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		Post:          q.Post.clone(db),
		PostsPriority: q.PostsPriority.clone(db),
		PostsReaction: q.PostsReaction.clone(db),
		PostsTag:      q.PostsTag.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:            db,
		Post:          q.Post.replaceDB(db),
		PostsPriority: q.PostsPriority.replaceDB(db),
		PostsReaction: q.PostsReaction.replaceDB(db),
		PostsTag:      q.PostsTag.replaceDB(db),
	}
}

type queryCtx struct {
	Post          IPostDo
	PostsPriority IPostsPriorityDo
	PostsReaction IPostsReactionDo
	PostsTag      IPostsTagDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Post:          q.Post.WithContext(ctx),
		PostsPriority: q.PostsPriority.WithContext(ctx),
		PostsReaction: q.PostsReaction.WithContext(ctx),
		PostsTag:      q.PostsTag.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
