// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNameUsersRelation = "users_relations"

// UsersRelation mapped from table <users_relations>
type UsersRelation struct {
	UsersRelationsID uint64         `gorm:"column:users_relations_id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"users_relations_id"`
	UserID           uint64         `gorm:"column:user_id;type:bigint(20) unsigned;not null;index:user_id,priority:1" json:"user_id"`
	RelatedUserID    uint64         `gorm:"column:related_user_id;type:bigint(20) unsigned;not null;index:related_user_id,priority:1" json:"related_user_id"`
	Relation         string         `gorm:"column:relation;type:varchar(20);not null;index:relation,priority:1" json:"relation"`
	CreatedAt        time.Time      `gorm:"column:created_at;type:timestamp;not null;default:current_timestamp()" json:"created_at"`
	DeletedAt        gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp" json:"deleted_at"`
	UpdatedAt        time.Time      `gorm:"column:updated_at;type:timestamp" json:"updated_at"`
}

// TableName UsersRelation's table name
func (*UsersRelation) TableName() string {
	return TableNameUsersRelation
}
