// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"fmt"
	"testing"

	"github.com/intxff/mango/notifications/internal/models"
	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := db.AutoMigrate(&models.Notification{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&models.Notification{}) fail: %s", err)
	}
}

func Test_notificationQuery(t *testing.T) {
	notification := newNotification(db)
	notification = *notification.As(notification.TableName())
	_do := notification.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(notification.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <notifications> fail:", err)
		return
	}

	_, ok := notification.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from notification success")
	}

	err = _do.Create(&models.Notification{})
	if err != nil {
		t.Error("create item in table <notifications> fail:", err)
	}

	err = _do.Save(&models.Notification{})
	if err != nil {
		t.Error("create item in table <notifications> fail:", err)
	}

	err = _do.CreateInBatches([]*models.Notification{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <notifications> fail:", err)
	}

	_, err = _do.Select(notification.ALL).Take()
	if err != nil {
		t.Error("Take() on table <notifications> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <notifications> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <notifications> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <notifications> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*models.Notification{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <notifications> fail:", err)
	}

	_, err = _do.Select(notification.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <notifications> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <notifications> fail:", err)
	}

	_, err = _do.Select(notification.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <notifications> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <notifications> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <notifications> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <notifications> fail:", err)
	}

	_, err = _do.ScanByPage(&models.Notification{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <notifications> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <notifications> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <notifications> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), clause.PrimaryKey)

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <notifications> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <notifications> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <notifications> fail:", err)
	}
}
