// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

import (
	"time"

	"gorm.io/gorm"
)

const TableNameNotification = "notifications"

// Notification mapped from table <notifications>
type Notification struct {
	NotificationID uint64         `gorm:"column:notification_id;type:bigint(20) unsigned;primaryKey;autoIncrement:true" json:"notification_id"`
	Status         string         `gorm:"column:status;type:varchar(20);not null;index:class,priority:3" json:"status"`
	Class          string         `gorm:"column:class;type:varchar(20);not null;index:class,priority:1" json:"class"`
	UserID         uint64         `gorm:"column:user_id;type:bigint(20) unsigned;not null;index:user_id,priority:1" json:"user_id"`
	ObjectID       uint64         `gorm:"column:object_id;type:bigint(20) unsigned;not null;index:class,priority:2" json:"object_id"`
	CreatedAt      time.Time      `gorm:"column:created_at;type:timestamp;not null;default:current_timestamp()" json:"created_at"`
	DeletedAt      gorm.DeletedAt `gorm:"column:deleted_at;type:timestamp" json:"deleted_at"`
	UpdatedAt      time.Time      `gorm:"column:updated_at;type:timestamp" json:"updated_at"`
}

// TableName Notification's table name
func (*Notification) TableName() string {
	return TableNameNotification
}
